### ISSUE TITLE
HTTP响应body为空

### ISSUE THREAD

**Issue by mengccmumu** [apache/dubbo-go-pixiu-samples#29]
**What happened**:
用go 启动自定义provider ，定义响应结果为
```
type Test struct { 
    Code int
    Msg string
    Data []map[string]interface{}
}
```
Data中interface{}有多重可能赋值，可能又是map[string]string,亦或者是struct
发起curl请求pi-xiu，响应HTTP CODE 为200，但是body内容为空, 查看pi-xiu标准输出日志确实有dubbo provider响应数据。
是因为解析失败所以body为空？

**What you expected to happen**:
期待响应body内容

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ma642** [comment]
same with https://github.com/apache/dubbo-go-pixiu/issues/569
